#!/usr/bin/perl

my $pwd;
use Cwd;
BEGIN {
    ($pwd = Cwd::abs_path($0)) =~ s[/[^/]*$][];
    print "pwd=$pwd\n";
}

use lib $pwd;
use KAcfg;

exec_docker(
            'run',
            [
             -it => -p => join(':',
                               cfg('listen_inet','0.0.0.0'),
                               cfg('listen_port','8000'),
                               80),
             '--name=ka-nginx',
             '--net=ka-network',
             vol("$root/etc/nginx.conf",'/etc/nginx/nginx.conf','ro'),
             '--volumes-from' => 'ka-captcha-data',
             vol("$root/etc",'/home/keno/ka-server/etc'),
             vol("$root/var",'/home/keno/ka-server/var'),
             vol("$root/var/www/public/api/api.css",'/home/keno/ka-server/var/www/public/api/api.css'),
             cfg('nginx-detach','-d') || (),
            ],
            'kenoantigen/ka-nginx'
           );

